#!/bin/bash
#
# Combine files with one line of header each into one single file with 
# only one line of header from the first file
#
# Usage: 
#   combineFilesWithHeader file1 file2 file3 file4 ... > combinedFile
#
# Anthony Ho, ahho@stanford.edu, 2/26/2015
# Last update 2/26/2015


# Define array of files
file_array=( $@ )

# Output header of the first file
head -n 1 ${file_array[0]}
awk 'FNR > 1' ${file_array[@]}
