#!/bin/bash
#
# Linux tool start ipython notebook server on Greendragon and 
# start a SSH tunnel for port forwarding
#
# Anthony Ho, ahho@stanford.edu, 2/20/2015
# Last update 2/20/2015

kill $(ps aux | grep "[i]python notebook --profile=nbserver" | awk '{print $2}')
kill $(ps aux | grep -E "$user.*[s]sh -N -f -L localhost:8888:localhost:8889" | awk '{print $2}')
