#!/bin/bash
#
# Linux tool to kill ipython notebook server on a remote server
#
# Anthony Ho, ahho@stanford.edu, 2/20/2015
# Last update 7/29/2015


# Define server and port
server=greendragon.stanford.edu
remote_port=8970


# Kill the ipython notebook server on the remote server
ssh $server 'kill $(ps aux | grep -E "$USER.*[i]python.*--port=$remote_port" | awk '\''{print $2}'\'')'
