#!/bin/bash
#
# Linux tool to kill ipython notebook server on Greendragon and 
# kill the current SSH tunnel for port forwarding
#
# Anthony Ho, ahho@stanford.edu, 2/20/2015
# Last update 2/20/2015


# Kill the ipython notebook server on Greendragon
ssh $greendragon 'kill $(ps aux | grep -E "$USER.*[i]python.*--port=8889" | awk '\''{print $2}'\'')'

# Kill the SSH tunnel for ipython notebook
kill $(ps aux | grep -E "$USER.*[s]sh -N -f -L localhost:8888:localhost:8889" | awk '{print $2}')
