#!/bin/bash
#
# Remove the last line of the given files
#
# Usage:
#   removeLastLineInCurrentDir file1 file2 file3 ...
# 
# Anthony Ho,  ahho@stanford.edu, 9/15/2014
# Last update 2/26/2015

files=$@

if [ "$(uname)" == "Darwin" ]  # Mac
then
    for file in $files
    do
	sed -i '' -e '$ d' $file
    done
elif [ "$(uname)" == "Linux" ]  # Linux
then
    for file in $files
    do
	sed -i '$ d' $file
    done
fi
