#!/bin/bash
#
# Linux tool to start ipython notebook server on a remote server
#
# Anthony Ho, ahho@stanford.edu, 2/20/2015
# Last update 7/29/2015


# Before you run this, you will have to set up a new ipython notebook profile as nbserver3 by running:
#
# $ ipython profile create nbserver3
#
# Customize the ~/.ipython/profile_nbserver3/ipython_notebook_config.py and ipython_kernel_config.py files as you wish, including adding a password

# Also, if you are running this on GreenDragon, you should pick a different remote port from mine...


# Define server and port
server=greendragon.stanford.edu
remote_port=8970


# Start ipython notebook server on remote server
ssh $server "nohup ipython notebook --profile=nbserver3 --no-browser --port=$remote_port &> /dev/null < /dev/null &"


# Now you can access ipython notebook remotely via https://greendragon.stanford.edu:$remote_port on your favorite web browser
